skip_vim_plugin "snipmate"
vim_plugin_task "tlib", "git://github.com/tomtom/tlib_vim.git"
vim_plugin_task "mwutils", "git://github.com/MarcWeber/vim-addon-mw-utils.git"
vim_plugin_task "snipmate2", "git://github.com/garbas/vim-snipmate.git"
vim_plugin_task "vim-latex", "git://github.com/micheljansen/vim-latex.git"
vim_plugin_task "asm8051", "git://github.com/vim-scripts/asm8051.vim.git"
vim_plugin_task "hc12-syntax", "git://github.com/vim-scripts/HC12-syntax-highlighting.git"
